from manim import *

cities = [            
    "s", "b", "a", "c", "d", "e", "f", "g", "h", 
    "i", "j", "k", "l",
    "m", "n", "o", "p",
    # "r", "q", 
    "t"
    ]

positions = {
    "s": LEFT*3.75+UP*1.1,
    "a": LEFT*2.23+UP*1.32, 
    "b": LEFT*2.93+UP*0.85,
    "c": LEFT*3.45+UP*-0.02, 
    "d": LEFT*2.5+UP*0.02,
    "e": LEFT*1.3+UP*0.95, 
    "f": LEFT*1.75+UP*0.35,
    "g": LEFT*2.0+UP*-0.47,
    "h": LEFT*3.0+UP*-1.0,
    "i": LEFT*0.15+UP*1.25,
    "j": LEFT*0.6+UP*0.25,
    "k": LEFT*1.0+UP*-0.15,
    "l": LEFT*1.75+UP*-1.2,
    "m": LEFT*2.85+UP*-1.75,
    "n": LEFT*-0.1+UP*0.6,
    "o": LEFT*-0.0+UP*-0.4,
    "p": LEFT*-0.5+UP*-0.05,
    "q": LEFT*4.1+UP*1.3,
    "r": LEFT*3.85+UP*1.6,
    "t": LEFT*-0.93+UP*0.47,
}

labelDirections = {
    "s": RIGHT+UP,
    "a": RIGHT+UP,
    "b": DOWN,
    "c": LEFT, 
    "d": DOWN,
    "e": RIGHT+UP, 
    "f": LEFT,
    "g": RIGHT, 
    "h": LEFT,
    "i": RIGHT+UP,
    "j": RIGHT,
    "k": DOWN,
    "l": RIGHT,
    "m": DOWN,
    "n": LEFT+UP,
    "o": LEFT,
    "p": DOWN,
    "q": LEFT, 
    "r": LEFT,
    "t": RIGHT, 
}

adjLists = {
    # "s": ["a", "b", "r", "q"],
    "s": ["a", "b"],
    "a": ["b", "e", "f", "s"],
    "b": [ "c", "d", "a", "s"],
    "c": ["b", "d", "h"], 
    "d": ["b", "c", "g", "k"],
    "e": ["a", "j"],
    "f": ["k", "j", "o", "a"], #-----------------
    "g": [ "d", "l", "m"], 
    "h": ["c"],
    "i": ["n"],
    "j": ["e", "f", "n", "o"],
    "k": ["d", "f"],
    "l": ["g"],
    "m": ["g"],
    "n": ["i", "j", "p", "t"],
    "o": ["f", "j"],
    "p": ["n", "t"], 
    "q": [ "s"], 
    "r": ["s"],
    "t": ["n", "p"] 
}

pathWeights = {
    # "s": [4, 2, 1, 1],
    "s": [4, 2],
    "a": [1, 4, 8, 4], 
    "b": [5, 6, 1, 2],
    "c": [5, 2, 7], 
    # "d": [6, 2, 3, 10],
    "d": [6, 2, 4, 10],
    # "e": [4, 4],
    "e": [4, 5],
    "f": [3, 5, 9, 8],
    "g": [3, 2, 10], 
    "h": [7],
    "i": [3],
    "j": [4, 5, 4, 8],
    "k": [10, 3],
    "l": [2],
    "m": [10],
    "n": [3, 4, 1, 2],
    "o": [9, 8],
    "p": [1, 2], 
    "q": [1], 
    "r": [1],
    "t": [2, 2] 
}

weightDirections = {
    # "s": [UP, DOWN, RIGHT+UP, LEFT+DOWN],
    "s": [UP, DOWN],
    "a": [DOWN+RIGHT, UP+RIGHT, LEFT, UP], 
    "b": [DOWN+RIGHT, LEFT, RIGHT, DOWN],
    "c": [LEFT, DOWN, LEFT], 
    "d": [RIGHT, DOWN, LEFT+DOWN, DOWN],
    "e": [RIGHT+UP, RIGHT+UP],
    "f": [LEFT+DOWN, UP, UP+RIGHT, LEFT],
    "g": [LEFT, RIGHT, RIGHT+DOWN], 
    "h": [LEFT],
    "i": [LEFT],
    "j": [RIGHT+UP, UP, LEFT+UP, RIGHT],
    "k": [DOWN, RIGHT+UP],
    "l": [RIGHT],
    "m": [RIGHT+DOWN],
    "n": [LEFT, UP, DOWN+LEFT, UP],
    "o": [LEFT+DOWN, RIGHT],
    "p": [DOWN+LEFT, RIGHT], 
    "q": [LEFT+DOWN], 
    "r": [RIGHT],
    "t": [UP, RIGHT] 
}

pathToCity = {
    'b' : ['b'],
    'a' : ['a'],
    "c" : ['b', 'c'],
    "e" : ['b', 'a', 'e'],
    "d" : ['a', 'b', 'd'],
    "f" : ['b', 'a', 'f'],
    "j" : ['a', 'e', 'j'],
    "g" : ['e', 'a', 'b', 'd', 'g'],
    "l" : ['l'],
    "h" : ['g', 'd', 'b', 'c', 'h'],
    "k" : ['c', 'b', 'a', 'f', 'k'],
    "n" : ['f', 'a', 'e', 'j', 'n'],
    "p" : ['p'],
    "t" : ['n', 't'],
}

